Desktop/omnitest/flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField
from flask_ckeditor import CKEditorField
from wtforms.validators import DataRequired



class PostForm(FlaskForm):
    title = StringField('Your Title', validators=[DataRequired()])
    content = CKEditorField('Your Content', validators=[DataRequired()])
    picture =FileField('Upload Your Post Image', validators=[FileAllowed(['jpg', 'png', 'jpeg', 'webp'])])
    submit = SubmitField('Post')

Desktop/omnitest/flaskblog/main/routes.py
from flask import request,Blueprint, render_template
from flaskblog.models import Post


main = Blueprint('main', __name__)
  



@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(per_page=9, page=page)
    # posts = Post.query.filter_by(title=str(current_user.username)).order_by(Post.date_posted.desc())
    return render_template('home.html', posts=posts)



@main.route("/about")
def about():
    return render_template('about.html', title='About')

Desktop/omnitest/flaskblog/posts/routes.py
from flask import flash,redirect, url_for, render_template, abort, request,Blueprint
from flaskblog.posts.forms import PostForm
from flaskblog.users.utils import save_post_picture
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form=PostForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_post_picture(form.picture.data)
        else:
            picture_file = 'default_post.jpg'
        post = Post(title=form.title.data, content=form.content.data, image_file=picture_file, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your Post has successfully been added', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', legend='NEW POST', form=form)




@posts.route("/post/<int:post_id>", methods=['GET', 'POST'])
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title='Post', post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author!=current_user:
        abort(403)
    form=PostForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_post_picture(form.picture.data)
            post.image_file=picture_file
        post.title=form.title.data
        post.content=form.content.data
        db.session.commit()
        flash('Your Post Has Been Updated', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method=='GET':
        form.title.data=post.title
        form.content.data=post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='UPDATE POST')






@posts.route("/post/<int:post_id>/delete", methods=['GET'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author!=current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your Post has been Deleted', 'success')
    return redirect(url_for('main.home'))


@posts.route("/post/<int:post_id>/delete_confirmation", methods=['GET', 'POST'])
@login_required
def delete_confirmation(post_id):
    post = Post.query.get_or_404(post_id)
    should_delete = True
    return render_template('post.html', post=post, should_delete=should_delete)

Desktop/omnitest/flaskblog/users/routes.py
from datetime import datetime
from flask import redirect, url_for, flash, request, render_template, Blueprint, session
from flask_login import current_user, login_user, logout_user, login_required
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog import bcrypt, db
from flaskblog.users.utils import save_profile_picture, send_reset_email
from flaskblog.models import User, Post



users = Blueprint('users', __name__)




@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form=RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password = hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created. You can now login', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)



@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form=LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash('You have been logged in successfully', 'success')
            next_page=request.args.get('next')
            return redirect(next_page or url_for('main.home'))
        else:
            flash('Unsuccessful login. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)







@users.route("/logout", methods=['GET', 'POST'])   
def logout():  
    logout_user()
    session.clear()
    flash('You have been logged out', 'info')
    return redirect(url_for('main.home'))
  



@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form=UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_profile_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username=form.username.data
        current_user.email=form.email.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('users.account'))
    elif request.method=='GET':
        form.username.data=current_user.username
        form.email.data=current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)





@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(per_page=9, page=page)
    return render_template('user_posts.html', posts=posts, user=user, title='User Posts')





@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form=RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An Email has been sent with instructions to reset your password', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)



@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if not user:
        flash('That is an invalid or expired token','warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password=hashed_password
        db.session.commit()
        flash('Your Password has now been updated! You are now able to Log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)





@users.context_processor
def inject_current_year():
    return {'current_year': datetime.utcnow().year}

Desktop/omnitest/flaskblog/templates/about.html
{% extends 'layout.html' %}
{% block content %}
    <div class="about-container" id="about-top">
        <div class="abt-img-container">
            <img src="{{ url_for('static', filename='post_pics/' + 'AB.jpg') }}" lazy="loading" class="about-us-pic"  alt="Ransford Addai">
        </div>

        <small class="RA">Ransford Addai</small>
        <h2>ABOUT OMNIBLOGS</h2>
        <p>Welcome to OMNIBLOGS! We are dedicated to sharing knowledge and insights on various topics that interest our readers. Our goal is to create a community where everyone can learn, share, and grow together.</p>

        <h2>Our Mission</h2>
        <p>Our mission is to provide high-quality, informative, and engaging content that adds value to our readers' lives. We believe in the power of knowledge and strive to make learning accessible and enjoyable for everyone.</p>

        <h2>How It Works</h2>
        <p>On OMNIBLOGS, users can create and write their own posts, add images to their posts, and manage their content easily. Here's a brief overview of what you can do:</p>
        <ul>
            <li><strong>Create and Write Posts:</strong> Users can register and log in to their accounts to start writing posts. Share your thoughts, experiences, and knowledge on topics that interest you.</li>
            <li><strong>Add Post Images:</strong> Enhance your posts by adding images. Simply upload an image while creating or editing your post to make it more visually appealing and engaging.</li>
            <li><strong>Edit Posts:</strong> Need to make changes to your post? No problem! You can edit your posts at any time to update information, correct mistakes, or improve your content.</li>
            <li><strong>Delete Posts:</strong> If you no longer want a post to be visible, you can delete it with ease. Manage your content and keep OMNIBLOGS tidy and relevant.</li>
        </ul>

        <h2>Join the Community</h2>
        <p>If you are passionate about writing and have something valuable to share, we would love to hear from you! Join us on this journey and become a part of our growing community. Register today and start contributing to the conversation.</p>

        <p>Thank you for visiting OMNIBLOGS. We hope you find the content here helpful and inspiring.</p>
    </div>
    <footer>
        <div class="home-footer-container">
            <h2 class="home-connect">Connect With Us:</h2>
            <div class="home-social-channels">
                <a href="https://www.instagram.com/addai_325/" target="_blank" class="home-ig"><i class="fa-brands fa-square-instagram"></i></a>
                <a href="https://www.linkedin.com/in/ransford-addai-72b30b280/" class="home-In" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
                <a href="https://web.facebook.com/ransford.addai.96" target="_blank" class="home-fb"><i class="fa-brands fa-square-facebook"></i></a>
                <a href="https://github.com/Addai325" target="_blank" class="home-github"><i class="fa-brands fa-square-github"></i></a>
                
            </div>
            <div class="home-nav-links">
                <a href="{{ url_for('main.about') }}" class="home-abt-lnk">About us</a>  |
                <a href="{{ url_for('main.home') }}" class="home-hme-lnk">Home</a>
                <a href="#about-top" class="home-bttop-link">Back to top &uarr;</a>

            </div>
            <div class="home-copyright">
                <small class="the-home-copyright">&copy; {{ curreny_year }} OMNIBLOGS. All rights reserved.</small>
            </div>
        </div>
    </footer>
{% endblock content %}

Desktop/omnitest/flaskblog/templates/home.html
{% extends 'layout.html' %}
{% block content %}
    <div class="home-content" id="home-top">
        {% for post in posts.items %}
            <div class="home-container">
                <h2 class="post-title"><a href="{{ url_for('posts.post', post_id=post.id) }}" class="title-link">{{ post.title }}</a></h2>
                {% if post.image_file %}
                    <img class="post-imaged" src="{{ url_for('static', filename='post_pics/' + post.image_file) }}" lazy="loading"   alt="Post image">
                {% endif %}
                
                <div class="aut-dte-img">
                    <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" lazy="loading"  class="post-pro-pic" alt="Author Profile picture">
                    <div class="aut-container"><a href="{{ url_for('users.user_posts', username=post.author.username) }}" class="post-aut">{{ post.author.username }}</a></div>
                    <div class="date-container"><small class="date">{{ post.date_posted.strftime('%Y-%m-%d') }}</small></div>
                </div>
                
            </div>
        {% endfor %}
    </div>
    <div class="pagination-container">
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <button class="pag-main-button"><a class="pag-main-link" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a></button>
                {% else %}
                    <button class="pag-button"><a class="pag-link" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a></button>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
    </div>
    <footer>
        <div class="footer-container">
            <h2 class="home-connect">Stay Connected:</h2>
            <div class="home-social-channels">
                <a href="https://www.instagram.com/addai_325/" target="_blank" class="home-ig"><i class="fa-brands fa-square-instagram"></i></a>
                <a href="https://www.linkedin.com/in/ransford-addai-72b30b280/" class="home-In" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
                <a href="https://web.facebook.com/ransford.addai.96" target="_blank" class="home-fb"><i class="fa-brands fa-square-facebook"></i></a>
                <a href="https://github.com/Addai325" target="_blank" class="home-github"><i class="fa-brands fa-square-github"></i></a>
                
            </div>
            <div class="home-nav-links">
                <a href="{{ url_for('main.about') }}" class="home-abt-lnk">About us</a>  |
                <a href="{{ url_for('main.home') }}" class="home-hme-lnk">Home</a>
                <a href="#home-top" class="home-bttop-link">Back to top &uarr;</a>

            </div>
            <div class="home-copyright">
                <small class="the-home-copyright">&copy; {{ current_year }} OMNIBLOGS. All rights reserved.</small>
            </div>
        </div>
    </footer>
    
{% endblock content %}

Desktop/omnitest/flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
        <title>OMNIBLOGS-{{ title }}</title>
    {% else %}
        <title>OMNIBLOGS-Your Simplified and Solid Blogs</title>
    {% endif %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link rel="icon" href="{{ url_for('static', filename='favicons/' + 'favicon.jpg') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='about.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='register.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='login.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='account.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='create_post.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='post.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='user_posts.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='reset_request.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='reset_token.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='errors.css') }}">
</head>  
<body>
    <header>
        <div class="mobile-own">
            <div class="main-header">
                <input type="checkbox" id="menuToggle" class="header-input">
                <div class="ob-lbl">
                    <a href="{{ url_for('main.home') }}" class="ob-link">OMNIBLOGS</a>
                    <label for="menuToggle" class="hamburger-menu">&#9776;</label>
                </div>
                
                <nav class="header-nav">
                    <div class="header-links-col">
                        <div class="reg-lgn">
                            {% if current_user.is_authenticated %}
                                <a href="{{url_for('posts.new_post') }}" onclick="CloseMenu()" class="crt">Create My Post</a         >
                                <a href="{{ url_for('users.account') }}"  onclick="CloseMenu()" class="acct">Account</a>
                                <a href="{{ url_for('users.logout') }}"  onclick="CloseMenu()" class="lgt">Logout</a>
                            {% else %}
                                <a href="{{ url_for('users.register') }}" onclick="CloseMenu()" class="reg">Register</a>
                                <a href="{{ url_for('users.login') }}" onclick="CloseMenu()" class="lgn">Login</a>
                            {% endif %}
                        </div>
                        <hr class="nav-line">
                        <div class="hme-abt">
                            <a href="{{ url_for('main.home') }}" onclick="CloseMenu()" class="hme">Home</a>
                            <a href="{{ url_for('main.about') }}" onclick="CloseMenu()" class="abt">About us</a>
                        </div>
                    </div>
                    
                    
                </nav>
            </div>    
    
        </div>
        <div class="desktop-own">
            <div class="main-header">
                
                <div class="ob-lbl">
                    <a href="{{ url_for('main.home') }}" class="ob-link">OMNIBLOGS</a>
                </div>
                
                <nav class="header-nav">
                    <div class="header-links-col">
                        <div class="hme-abt">
                            <a href="{{ url_for('main.home') }}" onclick="CloseMenu()" class="hme">Home</a>
                            <a href="{{ url_for('main.about') }}" onclick="CloseMenu()" class="abt">About us</a>
                        </div>
                        <div class="reg-lgn">
                            {% if current_user.is_authenticated %}
                                <a href="{{url_for('posts.new_post') }}" onclick="CloseMenu()" class="crt">Create My Post</a         >
                                <a href="{{ url_for('users.account') }}"  onclick="CloseMenu()" class="acct">Account</a>
                                <a href="{{ url_for('users.logout') }}"  onclick="CloseMenu()" class="lgt">Logout</a>
                            {% else %}
                                <a href="{{ url_for('users.register') }}" onclick="CloseMenu()" class="reg">Register</a>
                                <a href="{{ url_for('users.login') }}" onclick="CloseMenu()" class="lgn">Login</a>
                            {% endif %}
                        </div>
                    </div>
                    
                    
                </nav>
            </div>    
    
        </div>
            
    </header>
        {% with messages=get_flashed_messages(with_categories=True) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert {% if category=='success' %}alert-success{% elif category=='danger' %}alert-danger{% elif category=='warning' %}alert-warning{% elif category=='info' %}alert-info{% endif %}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
    
    {% block content %}{% endblock content %}
    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>
</html>

Desktop/omnitest/flaskblog/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <div class="lgn-container">
        <form method="post", action="">
            {{ form.hidden_tag() }}
            <fieldset class="the-fst">
                <legend class="lgn-legend">LOGIN</legend>
                
                <div>
                    {{ form.email.label(class='emll-lbl') }}
                    {% if form.email.errors %}
                        {{ form.email(class='emll-error', placeholder='Type your email...') }}
                        {% for error in form.email.errors %}
                            <span class="the-emll-error">{{ error }}</span>
                        {% endfor %}
                    {% else %}
                        {{ form.email(class='emll', placeholder='Type your email...') }}
                    {% endif %}
                </div>
                <div>
                    {{ form.password.label(class='pswd-lbl') }}
                    {% if form.password.errors %}
                        {{ form.password(class='pswd-error', placeholder='Input your password..') }}
                        {% for error in form.password.errors %}
                            <span class="the-pswd-error">{{ error }}</span>
                        {% endfor %}
                    {% else %}
                        {{ form.password(class='pswd', placeholder='Input your password..') }}
                    {% endif %}
                </div>
                <div class="rememb">
                    {{ form.remember(class='rememb-checkbox') }}
                    {{ form.remember.label(class='rememb-lbl') }}
                </div>
               
            </fieldset>
            <div>
                {{ form.submit(class='the-subbb') }}
            </div>
            <div class="forgot-pswd">
                <a href="{{ url_for('users.reset_request') }}" class="forgot-pswd-link"><small class="forgot">Forgot Password?</small></a>
            </div>
        </form>
        <div class="lgn-already">
            <small class="lgn-small-already">
                New user?<a class="lgn-already-link" href="{{ url_for('users.register') }}">Register here</a>
            </small>
        </div>
    </div>
{% endblock content %}

Desktop/omnitest/flaskblog/templates/post.html
{% extends 'layout.html' %}
{% block content %}
    <div class="post-content-top" id="post-top">
            <div class="post-container">
                <div>
                    <button class="update-button"><a class="update-link" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a></button>
                    <button class="del-confirm-button"><a class="del-confirm-link" href="{{ url_for('posts.delete_confirmation', post_id=post.id) }}">Delete</a></button>
                </div>
                <h1 class="posts-title">{{ post.title }}</h1>
                {% if post.image_file %}
                    <img class="posts-imaged" src="{{ url_for('static', filename='post_pics/' + post.image_file) }}" lazy="loading" alt="Post image">
                {% endif %}
                <p class="the-post-content">{{ post.content|safe }}</p>
                
                <div class="aut-dte-imgs">
                    <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" lazy="loading" class="posts-pro-pic" alt="Author Profile picture">
                    <div class="auts-container"><a href="{{ url_for('users.user_posts', username=post.author.username) }}" class="posts-aut">{{ post.author.username }}</a></div>
                    <div class="dates-container"><small class="posts-date">{{ post.date_posted.strftime('%Y-%m-%d') }}</small></div>
                </div>
                
            </div>
    </div>
    {% if should_delete %}
        <div class="delete-section">
            <div class="delete-confirm-container">
                <h2 class="del-conf">DELETE CONFRMATION</h2>
                <p class="sure-del">Are you sure you want to delete?</p>
                <form methods= "post" action="{{ url_for('posts.delete_confirmation', post_id=post.id) }}">
                    <button class="cancel-btn"><a class="cancel-lnk" href="{{ url_for('posts.post', post_id=post.id) }}">Cancel</a></button>
                    <button class="del-btn"><a class="del-lnk" href="{{ url_for('posts.delete_post', post_id=post.id) }}">Delete</a></button>
                </form>
            </div>
        </div>
    {% endif %}
    <footer>
        <div class="post-footer-container">
            <!-- <h2 class="home-connect">Stay Connected:</h2> -->
            <div class="home-social-channels">
                <a href="https://www.instagram.com/addai_325/" target="_blank" class="home-ig"><i class="fa-brands fa-square-instagram"></i></a>
                <a href="https://www.linkedin.com/in/ransford-addai-72b30b280/" class="home-In" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
                <a href="https://web.facebook.com/ransford.addai.96" target="_blank" class="home-fb"><i class="fa-brands fa-square-facebook"></i></a>
                <a href="https://github.com/Addai325" target="_blank" class="home-github"><i class="fa-brands fa-square-github"></i></a>
                
            </div>
            <div class="home-nav-links">
                <a href="{{ url_for('main.about') }}" class="home-abt-lnk">About us</a>  |
                <a href="{{ url_for('main.home') }}" class="home-hme-lnk">Home</a>
                <a href="#post-top" class="home-bttop-link">Back to top &uarr;</a>

            </div>
            <div class="home-copyright">
                <small class="the-home-copyright">&copy; {{ curreny_year }} OMNIBLOGS. All rights reserved.</small>
            </div>
        </div>
    </footer>
{% endblock content %}

Desktop/omnitest/flaskblog/templates/user_posts.html
{% extends 'layout.html' %}
{% block content %}
    <div class="user-posts-container" id="up-top"><h1 class="user-posts">Posts by {{ user.username }}({{ posts.total }})</h1></div>
    <div class="user-content">
        {% for post in posts.items %}
            <div class="user-container">
                <h2 class="user-title"><a href="{{ url_for('posts.post', post_id=post.id) }}" class="user-title-link">{{ post.title }}</a></h2>
                {% if post.image_file %}
                    <img class="user-post-imaged" src="{{ url_for('static', filename='post_pics/' + post.image_file) }}" lazy="loading" alt="Post image">
                {% endif %}
                <!-- <p class="post-content">{{ post.content }}</p> -->
                
                <div class="user-aut-dte-img">
                    <img src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" lazy="loading" class="user-pro-pic" alt="Author Profile picture">
                    <div class="user-aut-container"><a href="{{ url_for('users.user_posts', username=post.author.username) }}" class="user-aut">{{ post.author.username }}</a></div>
                    <div class="user-date-container"><small class="user-date">{{ post.date_posted.strftime('%Y-%m-%d') }}</small></div>
                </div>
                
            </div>
        {% endfor %}
    </div>
        <div class="user-pagination-container">
            {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                    {% if posts.page == page_num %}
                        <button class="user-pag-main-button"><a class="user-pag-main-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></button>
                    {% else %}
                        <button class="user-pag-button"><a class="user-pag-link" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a></button>
                    {% endif %}
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        </div>
        <footer>
            <div class="user_posts-footer-container">
                <!-- <h2 class="home-connect">Stay Connected:</h2> -->
                <div class="home-social-channels">
                    <a href="https://www.instagram.com/addai_325/" target="_blank" class="home-ig"><i class="fa-brands fa-square-instagram"></i></a>
                    <a href="https://www.linkedin.com/in/ransford-addai-72b30b280/" class="home-In" target="_blank"><i class="fa-brands fa-linkedin"></i></a>
                    <a href="https://web.facebook.com/ransford.addai.96" target="_blank" class="home-fb"><i class="fa-brands fa-square-facebook"></i></a>
                    <a href="https://github.com/Addai325" target="_blank" class="home-github"><i class="fa-brands fa-square-github"></i></a>
                    
                </div>
                <div class="home-nav-links">
                    <a href="{{ url_for('main.about') }}" class="home-abt-lnk">About us</a>  |
                    <a href="{{ url_for('main.home') }}" class="home-hme-lnk">Home</a>
                    <a href="#up-top" class="home-bttop-link">Back to top &uarr;</a>
    
                </div>
                <div class="home-copyright">
                    <small class="the-home-copyright">&copy; {{ curreny_year }} OMNIBLOGS. All rights reserved.</small>
                </div>
            </div>
        </footer>
    
    
{% endblock content %}